# Generated by Django 5.2.7 on 2025-11-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_task_end_date_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.CharField(default='v1.0', max_length=20, verbose_name='Версия проекта'),
        ),
    ]
