# Generated by Django 5.2.7 on 2025-11-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_subtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='available_statuses',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='has_kanban',
        ),
        migrations.AddField(
            model_name='task',
            name='has_kanban',
            field=models.BooleanField(default=False, verbose_name='Использовать канбан-доску для подзадач'),
        ),
        migrations.AddField(
            model_name='task',
            name='subtask_statuses',
            field=models.ManyToManyField(blank=True, related_name='kanban_tasks', to='projects.taskstatus', verbose_name='Статусы для подзадач'),
        ),
    ]
